var danceurls = [ 
    Script.resolvePath('./Animations/Ballet 372.fbx'),
    Script.resolvePath('./Animations/BBoy Look at me be Booooi 202.fbx'),
    Script.resolvePath('./Animations/Belly Dance 590.fbx'),
    Script.resolvePath('./Animations/Snaker 2step 64.fbx'),
    Script.resolvePath('./Animations/Beyonce Boogie 235.fbx'),
    Script.resolvePath('./Animations/Body Rocka 64.fbx'),
    Script.resolvePath('./Animations/Booty Booty Booty 148.fbx'),
    Script.resolvePath('./Animations/Breakdance 1990 16.fbx'),
    Script.resolvePath('./Animations/Chicken Dance 144.fbx'),
    Script.resolvePath('./Animations/Every day Im shuffelin 226.fbx'),
    Script.resolvePath('./Animations/Flair it Up 75.fbx'),
    Script.resolvePath('./Animations/Gangnam Style 372.fbx'),
    Script.resolvePath('./Animations/Hokey Pokey 351.fbx'),
    Script.resolvePath('./Animations/In Yo Own World 392.fbx'),
    Script.resolvePath('./Animations/Jiggle Jangle 474.fbx'),
    Script.resolvePath('./Animations/King Tut 509.fbx'),
    Script.resolvePath('./Animations/Mad attitude 184.fbx'),
    Script.resolvePath('./Animations/Raise the roof 124.fbx'),
    Script.resolvePath('./Animations/Runnin Man 326.fbx'),
    Script.resolvePath('./Animations/Salsa and Chips 566.fbx'),
    Script.resolvePath('./Animations/Salsa Papi 136.fbx'),
    Script.resolvePath('./Animations/Salsa spinna 79.fbx'),
    Script.resolvePath('./Animations/Shake it like you mean it 360.fbx'),
    Script.resolvePath('./Animations/Shoppin like its Costco 479.fbx'),
    Script.resolvePath('./Animations/Slider with cheese 520.fbx'),
    Script.resolvePath('./Animations/Smoov Playa 489.fbx'),
    Script.resolvePath('./Animations/So into it 244.fbx'),
    Script.resolvePath('./Animations/Swing Batta Batta 742.fbx'),
    Script.resolvePath('./Animations/Swing so happy 628.fbx'),
    Script.resolvePath('./Animations/Swinga 700.fbx'),
    Script.resolvePath('./Animations/Thriller Idle 131.fbx'),
    Script.resolvePath('./Animations/Thriller Part 1 896.fbx'),
    Script.resolvePath('./Animations/Thriller Part 2 566.fbx'),
    Script.resolvePath('./Animations/Thriller Part 3 768.fbx'),
    Script.resolvePath('./Animations/Thriller Part 4 1113.fbx'),
    Script.resolvePath('./Animations/Twerk it Twerk it 457.fbx'),
    Script.resolvePath('./Animations/Twista 284.fbx'),
    Script.resolvePath('./Animations/Wavy baby 213.fbx'),
    Script.resolvePath('./Animations/Ymca Dance 136.fbx')
];

module.exports = danceurls;
